### ISSUE TITLE
Running in production backtraces

### ISSUE THREAD

**Issue by wr0ngway** [hyperstack-org/hyperstack#109]
I tried running a minimal app in `RAILS_ENV=production` and get the following trace.
If I disable eager_load, it just delays the trace till an action is performed.  Did I miss some config or ...?

```
app_1       | /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require': No such file to load -- models/application_record.rb (LoadError)
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
app_1       | 	from /srv/app/app/models/application_record.rb:5:in `<top (required)>'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `load_interlock'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:356:in `require_or_load'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:334:in `depend_on'
app_1       | 	from /srv/bundler/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:246:in `require_dependency'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/engine.rb:477:in `each'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/engine.rb:477:in `block in eager_load!'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/engine.rb:475:in `each'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/engine.rb:475:in `eager_load!'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/engine.rb:356:in `eager_load!'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `each'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
app_1       | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
app_1       | 	from /srv/app/config/environment.rb:5:in `<top (required)>'
app_1       | 	from config.ru:3:in `require_relative'
app_1       | 	from config.ru:3:in `block in <main>'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
app_1       | 	from config.ru:in `new'
app_1       | 	from config.ru:in `<main>'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:27:in `app'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
app_1       | 	from /srv/bundler/gems/rack-2.0.6/lib/rack/server.rb:283:in `start'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:53:in `start'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `tap'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `perform'
app_1       | 	from /srv/bundler/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
app_1       | 	from /srv/bundler/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
app_1       | 	from /srv/bundler/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
app_1       | 	from /srv/bundler/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
app_1       | 	from /srv/app/bin/rails:9:in `require'
app_1       | 	from /srv/app/bin/rails:9:in `<top (required)>'
app_1       | 	from /srv/bundler/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
app_1       | 	from /srv/bundler/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
app_1       | 	from /srv/bundler/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
app_1       | 	from /srv/bundler/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
app_1       | 	from /srv/bundler/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
app_1       | 	from /srv/bundler/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
app_1       | 	from /srv/bundler/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
app_1       | 	from /srv/app/bin/spring:15:in `require'
app_1       | 	from /srv/app/bin/spring:15:in `<top (required)>'
app_1       | 	from bin/rails:3:in `load'
app_1       | 	from bin/rails:3:in `<main>'
```

**Comment by catmando** [comment]
@wr0ngway we need some better documentation on production config.

It's not too hard, but I don't know the details... I'll ask on the gitter chat area, and post the answer when it comes up.  Stay tuned.

**Comment by wr0ngway** [comment]
Thanks, I wasn't trying to actually run in production, just trying to bring it up locally as production to see if it would eliminate a performance problem (rails spending 20s rendering assets on a page reload).  The problems seems to have something to do with the load paths and the funkiness done to share models between client/server.  To duplicate:

```
rails new foo --skip-test --template=https://rawgit.com/hyperstack-org/hyperstack/edge/install/rails-webpacker.rb
```
config/cable.yml:
```
production:
  adapter: async
```
Removed production qualifiers from app/policies/application_policy.rb

```
RAILS_ENV=production bundle exec foreman start
```
```
16:42:43 web.1  | => Rails 5.2.2 application starting in production 
16:42:43 web.1  | => Run `rails server -h` for more startup options
16:42:44 web.1  | /Users/mconway/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': No such file to load -- models/application_record.rb (LoadError)
```

**Comment by catmando** [comment]
closing
