### ISSUE TITLE
superclass mismatch for class Application

### ISSUE THREAD

**Issue by BillyRuffian** [hyperstack-org/hyperstack#139]
Starting from scratch, 

```
rails new Hyperstack --template=https://rawgit.com/hyperstack-org/hyperstack/edge/install/rails-webpacker.rb
```

```
cd Hyperstack
foreman start
16:40:51 web.1  | started with pid 37654
16:40:51 hot.1  | started with pid 37655
16:40:52 hot.1  | Listening on port 25222, watching for changes in app/hyperstack/, app/assets/javascripts, app/assets/stylesheets
16:40:52 hot.1  | opal-hot-reloader: starting...
16:40:53 web.1  | /Users/___/Projects/NBT/Hyperstack/config/application.rb:10:in `<module:Hyperstack>': superclass mismatch for class Application (TypeError)
16:40:53 web.1  | 	from /Users/___/Projects/NBT/Hyperstack/config/application.rb:9:in `<main>'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2.1/lib/rails/command/base.rb:65:in `perform'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2.1/lib/rails/command.rb:46:in `invoke'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2.1/lib/rails/commands.rb:18:in `<main>'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
16:40:53 web.1  | 	from /Users/___/Projects/NBT/Hyperstack/bin/rails:9:in `<top (required)>'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
16:40:53 web.1  | 	from /Users/___/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
16:40:53 web.1  | 	from /Users/___/Projects/NBT/Hyperstack/bin/spring:15:in `require'
16:40:53 web.1  | 	from /Users/___/Projects/NBT/Hyperstack/bin/spring:15:in `<top (required)>'
16:40:53 web.1  | 	from bin/rails:3:in `load'
16:40:53 web.1  | 	from bin/rails:3:in `<main>'
16:40:53 web.1  | exited with code 1
16:40:53 system | sending SIGTERM to all processes
16:40:54 hot.1  | terminated by SIGTERM
```

**Comment by BillyRuffian** [comment]
My bad, shouldn't have been quite the idiot in creating a project called 'Hyperstack'.
