### ISSUE TITLE
Hotloader is throwing a "file not found" error when I try to run `bundle exec foreman start`

### ISSUE THREAD

**Issue by lillykulp** [hyperstack-org/hyperstack#419]
I'm trying to run hyperstack on wsl (kali). I'm following the tutorial for the todo app on the website, but when I get to the point where I should be doing the first test run of the project, hotloader throws a file not found error and borks the project. There are no issues when running a vanilla rails app.

This is the output:

```17:24:01 web.1        | started with pid 28574
17:24:01 hot-loader.1 | started with pid 28575
17:24:02 hot-loader.1 | /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/adapter/config.rb:16:in `realpath': No such file or directory @ rb_check_realpath_internal - app/hyperstack (Errno::ENOENT)
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/adapter/config.rb:16:in `realpath'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/adapter/config.rb:16:in `block in initialize'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/adapter/config.rb:15:in `map'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/adapter/config.rb:15:in `initialize'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/backend.rb:27:in `new'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/backend.rb:27:in `initialize'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/listener.rb:49:in `new'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen/listener.rb:49:in `initialize'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen.rb:30:in `new'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/listen-3.7.0/lib/listen.rb:30:in `to'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/hyperstack-config-1.0.alpha1.8/lib/hyperstack/hotloader/server.rb:106:in `loop'
17:24:02 hot-loader.1 |         from /var/lib/gems/2.7.0/gems/hyperstack-config-1.0.alpha1.8/bin/hyperstack-hotloader:22:in `<top (required)>'
17:24:02 hot-loader.1 |         from /usr/local/bin/hyperstack-hotloader:23:in `load'
17:24:02 hot-loader.1 |         from /usr/local/bin/hyperstack-hotloader:23:in `<main>'
17:24:02 hot-loader.1 | Listening on port 25222, watching for changes in app/hyperstack, app/assets/stylesheets
17:24:02 web.1        | => Booting Puma
17:24:02 web.1        | => Rails 6.1.4.1 application starting in development 
17:24:02 web.1        | => Run `bin/rails server --help` for more startup options
17:24:02 hot-loader.1 | exited with code 1
17:24:02 system       | sending SIGTERM to all processes
17:24:02 web.1        | Exiting
17:24:03 web.1        | terminated by SIGTERM```

**Comment by lillykulp** [comment]
The issue disappeared after I nuked the project and started over, presumably I made a mistake somewhere.
